name: nightly if changes last 24h
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v2

      - name: Check for changes last 24 hours that modified src/plugin folder
        id: should_run
        shell: bash
        run: echo "should_run=$(git log --since="1 days ago" --name-only | grep 'src/plugin/.*' -c)" >> "$GITHUB_OUTPUT"

  release-spriggit:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.should_run == 1 }}
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Spriggit
        uses: FlayaN/spriggit-runner-action@fbd43cea737ad3bb6b94f9985fa206691a9017b1
        with:
          spriggit_tool_version: "0.5"
          spriggit_args: deserialize -i ${{ github.workspace }}/src/plugin -o ${{ github.workspace }}/TestMod.esm

      - name: Delete Existing Release
        uses: dev-drprasad/delete-tag-and-release@v1.0
        with:
          tag_name: nightly
          github_token: ${{ secrets.GITHUB_TOKEN }}
          delete_release: true

      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.13.0
        with:
          allowUpdates: true
          name: Nightly
          draft: false
          body: Nightly release of the latest patch
          tag: nightly
          prerelease: true
          makeLatest: true
          removeArtifacts: true
          replacesArtifacts: true
          artifacts: ${{ github.workspace }}/TestMod.esm
