name: spriggit release
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:
jobs:
  check-changes:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.should_run.outputs.should_run }}
    steps:
      - uses: actions/checkout@v2

      - name: debug
        shell: bash
        run: git log --since="1 days ago" --name-only

      - name: Check for changes last 24 hours that modified src/plugin folder
        id: should_run
        shell: bash
        run: echo "should_run=$(git log --since="1 days ago" --name-only | grep 'src/plugin/.*' -c)" >> "$GITHUB_OUTPUT"

      - name: debug output
        shell: bash
        run: echo "${{ steps.should_run.outputs.should_run }}"

  release-spriggit:
    needs: check-changes
    if: ${{ needs.check-changes.outputs.should_run == 1 }}
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Spriggit
        uses: FlayaN/spriggit-runner-action@fbd43cea737ad3bb6b94f9985fa206691a9017b1
        with:
          spriggit_tool_version: "0.5"
          spriggit_args: deserialize -i ${{ github.workspace }}/src/plugin -o ${{ github.workspace }}/TestMod.esm

      - uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifacts: ${{ github.workspace }}/TestMod.esm
